# Generated by Django 5.0.2 on 2024-02-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='state',
        ),
    ]
